#!/usr/bin/env bash

rm -f compile_flags.txt
echo "-I" >> compile_flags.txt
# IS_NIX := $(shell which nix > /dev/null 2>&1 && echo yes || echo no)
if which nix > /dev/null 2>&1; then
	echo "$(nix-store -r $(which postgres) 2>/dev/null)/include/server" >> compile_flags.txt
else
	PG_CONFIG = pg_config
	echo "$(pg_config --includedir-server)" >> compile_flags.txt
fi
